"""create flight tables

Revision ID: 5a4486324e1c
Revises: f617788ad4de
Create Date: 2026-06-17 10:00:18.410633
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a4486324e1c'
down_revision: Union[str, None] = 'f617788ad4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airports',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('flights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('airline_id', sa.String(length=36), nullable=True),
    sa.Column('departure_airport_code', sa.String(length=20), nullable=True),
    sa.Column('arrival_airport_code', sa.String(length=20), nullable=True),
    sa.Column('flight_number', sa.String(length=10), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('cabin_class', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['arrival_airport_code'], ['airports.code'], ),
    sa.ForeignKeyConstraint(['departure_airport_code'], ['airports.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###