"""add selected_seat to bookings and create seats table

Revision ID: b7b936239bd5
Revises: 57238ffce076
Create Date: 2026-06-24 08:13:57.435877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7b936239bd5'
down_revision: Union[str, None] = '57238ffce076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flight_id', sa.String(length=36), nullable=False),
    sa.Column('seat_label', sa.String(length=10), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.add_column('bookings', sa.Column('selected_seat', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'selected_seat')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###