"""init tables

Revision ID: f617788ad4de
Revises: 
Create Date: 2026-06-17 08:25:26.061345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f617788ad4de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###